# Generated by Django 5.1.6 on 2025-06-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
