# Generated by Django 5.2.1 on 2025-06-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersessionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSessionLog',
        ),
    ]
